const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOG_OUT: "LOG_OUT",
    CHANGE_PASS: "CHANGE_PASS",

    GET_ALL_RHS: "GET_ALL_RHS",
    GET_RHS: "GET_RHS",
    GET_RHS_LIMIT: "GET_RHS_LIMIT",
    GET_RHS_PUBLIC_BY_USER: "GET_RHS_PUBLIC_BY_USER",
    GET_RHS_BY_USER: "GET_RHS_BY_USER",
    GET_RHS_BY_USER_UNPAY: "GET_RHS_BY_USER_UNPAY",
    GET_NEW_RH: "GET_NEW_RH",
    GET_PRICES: "GET_PRICES",
    GET_AREAS: "GET_AREAS",
    GET_PROVINCES: "GET_PROVINCES",
    GET_NEW_POST: "GET_NEW_POST",

    GET_TRANSACTION_TYPES: "GET_TRANSACTION_TYPES",
    GET_REAL_HOME_TYPES: "GET_REAL_HOME_TYPES",
    GET_REAL_HOME_TYPES_BY_TRANS: "GET_REAL_HOME_TYPES_BY_TRANS",

    // USER
    GET_All_LIMIT_USER: "GET_All_LIMIT_USER",
    GET_All_USER: "GET_All_USER",
    GET_USER: "GET_USER",
    GET_SAVE_POST: "GET_SAVE_POST",
    GET_SAVE_POST_LIMIT: "GET_SAVE_POST_LIMIT",
    GET_DETAIL_POST: "GET_DETAIL_POST",
    RH_EDIT: "RH_EDIT",
    DEL_DATA_EDIT: "DEL_DATA_EDIT",

    //PAYMENT
    GET_PAY_HIS_LIMIT_BY_USER: "GET_PAY_HIS_LIMIT_BY_USER",
    GET_NEWS_TYPE: "GET_NEWS_TYPE",

    // BLOG
    GET_ALL_BLOG: "GET_ALL_BLOG",
    GET_ALL_LIMIT_BLOG: "GET_ALL_LIMIT_BLOG",
    GET_DETAIL_BLOG: "GET_DETAIL_BLOG",

    // BLOG TYPE
    GET_ALL_BLOG_TYPE: "GET_ALL_BLOG_TYPE",
};

export default actionTypes;
